### ISSUE TITLE
你好，如何部署自己训练的模型呢？

### ISSUE THREAD

**Issue by jack1yang** [zhangqijun/deeplearningdemo#11]
你好！ 非常感谢你开源的项目。最近在学习模型部署，但是我发现您给的都是docker镜像。 那怎么使用自己的模型进行推理展示呢？

**Comment by jack1yang** [comment]
或者说你根据model创建docker镜像的文件，可以分享一下吗

**Comment by zhangqijun** [comment]
部署自己的模型的话，需要按照之前的模型找个类似的模版，然后复制更改添加一下自己的推理代码。
