### ISSUE TITLE
manifest unknown: manifest unknown

### ISSUE THREAD

**Issue by xiaogift** [zhangqijun/deeplearningdemo#14]
安装过程中
docker pull zzz9958123/densepose

$ sudo docker pull zzz9958123/densepose
Using default tag: latest
Error response from daemon: manifest for zzz9958123/densepose:latest not found: manifest unknown: manifest unknown

**Comment by zhangqijun** [comment]
latest是没有的，参考这个tag
https://hub.docker.com/repository/docker/zzz9958123/densepose

**Comment by xiaogift** [comment]
docker pull zzz9958123/densepose:c2-cuda10.1-cudnn7
