### ISSUE TITLE
ERROR: Encountered errors while bringing up the project.

### ISSUE THREAD

**Issue by xiaogift** [zhangqijun/deeplearningdemo#15]
docker compose-up
$ sudo docker-compose up
WARNING: The PWD variable is not set. Defaulting to a blank string.
deeplearningdemo_ocrserver_1 is up-to-date
deeplearningdemo_ocrmypdf-web_1 is up-to-date
deeplearningdemo_chineseocr_1 is up-to-date
Creating deeplearningdemo_demo_gpu_server_1 ... error
Creating deeplearningdemo_demo_cpu_server_1 ...

ERROR: for deeplearningdemo_demo_gpu_server_1  Cannot create container for service demo_gpu_server: b'invalid volume specification: \'.:.:rw\': invalid mount config for type "volume": invalid mount path: \'.\' mount path must be absoluteCreating deeplearningdemo_demo_cpu_server_1 ... error

ERROR: for deeplearningdemo_demo_cpu_server_1  Cannot create container for service demo_cpu_server: b'invalid volume specification: \'.:.:rw\': invalid mount config for type "volume": invalid mount path: \'.\' mount path must be absolute'

ERROR: for demo_gpu_server  Cannot create container for service demo_gpu_server: b'invalid volume specification: \'.:.:rw\': invalid mount config for type "volume": invalid mount path: \'.\' mount path must be absolute'

ERROR: for demo_cpu_server  Cannot create container for service demo_cpu_server: b'invalid volume specification: \'.:.:rw\': invalid mount config for type "volume": invalid mount path: \'.\' mount path must be absolute'

**Comment by zhangqijun** [comment]
WARNING: The PWD variable is not set. Defaulting to a blank string.
应该是docker-compose.yml里的$PWD为空导致的吧，试试填一下绝对路径吧

**Comment by xiaogift** [comment]
> WARNING: The PWD variable is not set. Defaulting to a blank string.
> 应该是docker-compose.yml里的$PWD为空导致的吧，试试填一下绝对路径吧

替换绝对路径okay，服务起来了，非常感谢。另外模型路径好像错了，模型打不开，model目录是在deeplearningdemo根目录下面吗?

**Comment by xiaogift** [comment]
> WARNING: The PWD variable is not set. Defaulting to a blank string.
> 应该是docker-compose.yml里的$PWD为空导致的吧，试试填一下绝对路径吧

okay了，谢谢
