### ISSUE TITLE
Version in "./docker-compose.yml" is unsupported. 

### ISSUE THREAD

**Issue by feiruyun** [zhangqijun/deeplearningdemo#7]
按照您微信公众号里的 说明**https://mp.weixin.qq.com/s/xdiB6Sx18hEK8urPkf0prA**
取消https功能后，运行docker-compose up
报错如下:
Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

请问，怎么解决？

**Comment by feiruyun** [comment]
docker-compose.yml文件中，修改version: "2.0"，后运行docker-compose up，一直卡在：
demo_cpu_server_1  | 
demo_cpu_server_1  | WARNING:tensorflow:From /home/deeplearningdemo-master/src/attribute_predict/attribute_predict_inference.py:22: The name tf.GraphDef is deprecated. Please use tf.compat.v1.GraphDef instead.
demo_cpu_server_1  |

**Comment by zhangqijun** [comment]
首先建议您使用如下方式安装最新的docker-compose,以支持3.3版本的yml。
```
sudo curl -L https://github.com/docker/compose/releases/download/1.23.1/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
docker-compose --version
```
即使不升级docker-compose,修改version: "2.0"，后运行docker-compose up应当也是可以的。卡住的那条仅仅是警告信息，建议查看本地5000端口是否服务已启动，如未启动，建议继续排查是否存在报错。建议先将主镜像pull下来。
`docker pull zzz9958123/demo_server`

**Comment by feiruyun** [comment]
主镜像已经pull下来了，docker-compose up后出现如下错误：
```
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 200).
```
虽然报错，但是http://0.0.0.0:5000/可以访问。
现在，我有以下几个问题：
1.本地部署后，本地本地镜像只启动了zzz9958123/demo_server（5000和5001端口），其他项目镜像都没有启动。
2.http://0.0.0.0:5000/页面中，所有的项目都不是本地部署的，都是访问您部署的URL。
3.怎样在本地部署项目？

感谢解答。

**Comment by zhangqijun** [comment]
1.本地部署后，只会使用主镜像。当具体的项目被调用的时候才会使用项目镜像。
2.访问的url地址是写在 `deeplearningdemo/templates/index.html` 文件中的地址。
3.http://0.0.0.0:5000/ 可以访问，本地部署已经完成了。

**Comment by feiruyun** [comment]
非常感谢，我还有些问题想咨询：
1.这些项目镜像是您打包封装的吧？
2.您是用什么工具打包封装的？
3.如果我想把自己的项目打包封装成镜像调用，应该怎么操作？
感谢解答！@zhangqijun

**Comment by zhangqijun** [comment]
1.有的是自己封装的，有的是官方的。
2.工具是docker封装为镜像，需要自己封装的每个项目单独写dockerfile。
3.自己封装的话只要你本地python可执行结果，即可将依赖做成镜像，利用编写dockerfile打包封装。

**Comment by feiruyun** [comment]
非常感谢！
联通网研院也开发了一套和您这个平台有点类似的平台，也提供了docker镜像打包工具，使用也很方便：[https://github.com/cube-ai/cubeai](https://github.com/cube-ai/cubeai)
您也可以看看。

**Comment by zhangqijun** [comment]
好的，研究一下。现在关闭这个issue了。
